"""Odoo-style source-of-truth contract, distinct from sales channels."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class CatalogProvider(Protocol):
    def get_product(self, product_id: str | int) -> dict[str, Any]: ...
    def create_draft(self, **values: Any) -> dict[str, Any]: ...
    def update_product(self, product_id: str | int, **values: Any) -> dict[str, Any]: ...
    def get_stock(self, product_id: str | int) -> dict[str, Any]: ...
    def update_stock(self, product_id: str | int, quantity: float) -> dict[str, Any]: ...
    def publish(self, product_id: str | int, **kwargs: Any) -> dict[str, Any]: ...
    def get_public_product(self, product_id: str | int) -> dict[str, Any]: ...
